ManyuDhyani/Event-Rally

config/mongoCollections.js, config/mongoConnection.js, config/settings.json
This request contain connection files for MongoDB. The database name is **EventRally**. The collections for the project include:   users, profile, event, comment, followers, and report.
=> Adding Config files for DB connection

.gitignore, package-lock.json, package.json
Created package.json  and configure it with initial required dependencies.
=> config package json for the project

data/comments.js, data/index.js, data/validation.js
Also added the comment data function for saving any new incoming comments.
=> Added data folder: It contain data function for database operation

data/reports.js
This is responsible for storing report data to report collection and returning the status of successful insertion of data.
=> Implemented report data function

data/likes.js
This is for likes sub document.
=> Implemented the like data function for event collection

data/likes.js
Once a new like objects come for a event to get saved, we have to add to the corresponding event and return the new count of like and dislike.
=> Calculate the Count of the Like and dislike.

data/validation.js
Also setup the validation.js file. Here all the validation function will be written for data and routes functions.
=> ID object validation Function

data/validation.js
This include validation for username, password, email, active, admin and verified fields of users data collection.
=> Validation function for users data

data/users.js
In this I have implemented these functions|: createUser, checkUser, getAllUsers
=> Users data functions implementations

data/users.js
Also changed return value for check user. We want user object to display user info in various pages.
=> Integrated the user field validation

app.js, data/events.js, public/css/main.css, public/js/main.js, routes/index.js
Config the server settings and other files like routes and public
=> Routes and public setup

data/comments.js, data/events.js, data/followers.js, data/index.js, data/likes.js, data/reports.js, data/users.js, package.json, routes/index.js, routes/users.js
Users routes include the routes for the login, register and related URLs.
=> User routes and correcting the paths for other files

data/events.js
Functions to create and update the event
=> Event data functions

data/comments.js
In this two type of function will be implemented. One to get parent comment and other the child comments for that parent comment when the thread is expanded.
=> Implemented the get comment function for event

public/js/registerForm.js, views/userRegister.handlebars
This commit includes the register form submission by use of ajax and also client side validation for password field.
=> Implemented the Register form submission by Ajax and client-side Validations

views/layouts/main.handlebars, views/userLogin.handlebars, views/userRegister.handlebars
Setup bootstrap files in main layout. Created Navbar in main layout. Added bootstrap in register and login page.
=> Bootstrap setup and added frontend for users view

data/profile.js, public/js/registerForm.js, routes/users.js, views/layouts/main.handlebars, views/profile.handlebars
with design (html/css) passed data to profile handlebars. Bug right now is handlebar don't evaluate logic operators like ==, !=, etc. Need to add helper function to check for conditions.
=> Designed the user profile page

app.js, data/validation.js, package-lock.json, package.json, views/profile.handlebars
Also Added helpers and partials as parameters for the express-handlebars
=> Added handlebars helper functions for Profile page

routes/comments.js, routes/followers.js, routes/index.js, routes/likes.js, routes/reports.js
Also created a folder for reports handlebar
=> routes for followers, likes, comments and reports

data/events.js, data/validation.js, package-lock.json, package.json, routes/events.js, routes/index.js, views/events/event.handlebars, views/events/eventCreateForm.handlebars, views/layouts/main.handlebars
Event Routes and Handlebars. Updates in Validations
=> Event Routes, Event Handlerbars and Validations

app.js, data/admin.js, data/users.js, package.json, routes/admin.js, routes/users.js, views/adminDashboardUsers.handlebars
In this I implemented a function to make a user as a verified user or vice-versa. Also created the middleware to use methods like Put, Patch or delete.
=> Created Request Middleware and Added verified user Functionality

data/events.js, public/js/eventInteraction.js, routes/events.js, views/events/event.handlebars
Added ajax for follow-unfollow functionality
=> Added ajax for follow unfollow functionality

data/likes.js, public/js/eventInteraction.js, routes/events.js, views/events/event.handlebars
Added ajax for likes dislikes and counts
=> Added ajax for likes dislikes and counts

data/events.js, data/validation.js, views/profileDetails.handlebars
Added following and attending total counts functions
=> Added following and attending total counts functions

app.js, data/reports.js, data/validation.js, routes/admin.js, routes/reports.js, routes/userProfile.js, routes/users.js, views/adminDashboardReports.handlebars, views/adminDashboardUsers.handlebars, views/error.handlebars, views/events/event.handlebars, views/layouts/main.handlebars, views/partials/reportComment.handlebars, views/partials/reportEvent.handlebars, views/partials/reportUser.handlebars, views/profile.handlebars
The admin dashboard is completed including verified user and report dashboard.
=> Implementation: Admin Report Dashboard and some bugs fix

data/comments.js, data/events.js, data/followers.js, data/likes.js, data/reports.js, data/users.js, routes/events.js, views/events/latest.handlebars, views/layouts/main.handlebars
Implemented the Latest Events. ALso changed the timestamp or created field in various collections to new Date() instead of string to make sort({timestamp: -1}) working.
=> Latest Events Features and fixed timestamp to ISODate

data/events.js, data/profile.js, routes/events.js, views/events/event.handlebars
Give out Graph like Attendee vs Followers, Attendee Gender Distribution, Followers Gender Distribution, Likes vs Dislikes on the event detail page.
=> First Extra Feature: Statistic Data on Event Detail Page

data/events.js, routes/events.js, routes/users.js, views/index.handlebars, views/layouts/main.handlebars
Bug fix and added trending functionality
=> Bug fix and added trending functionality

public/css/main.css, routes/events.js, views/events/event.handlebars, views/partials/searchform.handlebars
Main Page UI changes and similar events by categories on event page
=> Main Page UI changes and similar events by categories on event page
